### ISSUE TITLE
google protect block the apk 

### ISSUE THREAD

**Issue by pretech86** [D3VL/L3MON#109]
google protect blocked the apk file

**Comment by Jack-Rogers** [comment]
Yep, I'm aware of this issue, unfortunately it turns out when you release a tool online built for business, you can't trust the internet and it ends up getting used for bad things 😔 
Because of this, I won't be rebuilding the APK for public release, though anyone that has a genuine use for this software can email us for an updated version 👍

**Comment by pretech86** [comment]
how can i contact you

**Comment by Jack-Rogers** [comment]
I must stress that this is only for business enquiries ONLY - contact@d3vl.com

**Comment by pretech86** [comment]
I send you mail but you not reply
