### ISSUE TITLE
Not Getting Files

### ISSUE THREAD

**Issue by i-am-nuralam** [D3VL/L3MON#33]
I have hosted this on aws.
But it's not sending the files or not showing any file manager data.

**Comment by Jack-Rogers** [comment]
Sorry, I'm not able to login to your installation. 
Please check that you have given the application all the required permissions when installing, otherwise, it will not be able to access the files. 
Additionally, it's probably not a great idea publicly posting the link to your installation.

To address your issue, could you please have a look at the logs for any errors?

**Comment by Jack-Rogers** [comment]
closing as a non-issue. no further logs have been provided.
