### ISSUE TITLE
GPS view Improvment

### ISSUE THREAD

**Issue by OfficialBerg** [D3VL/L3MON#80]
**Is your feature request related to a problem? Please describe.**
- Yes and no

**Describe the solution you'd like**
I'd like to see more in depth map visuals or at least coordinates displayed over the tag for the location on the map.

**Describe alternatives you've considered**
I've going on the mapping site to change the settings to a satellite type view and there is no option.

**Additional context**
I know this would probably mean switching to an entirely new mapping api or something like that but it was just a thought for you guys. It would be nice to have a satellite type view for the GPS option.

**Comment by yatharthmaheshwari** [comment]
thanks for acknowledging this part of L3MON

-If you try to find the location of a person By using a Grabify Link(tracks ip -address) in most cases it will show the location about 1-200 kilometers(it varies ).
-this is because Tracking someone's ip address is very inaccurate(You can research it)
-if L3MON uses this way of tracking then it is not good.(i don't khow how it tracks location)

Once my relatives were visiting My house and got lost.
-so they decided to give there gps location using whatsapp which was extremely accurate.

**so think they might use the google API which costs around $5 which will be very accurate**

**Comment by Jack-Rogers** [comment]
Hey @OfficialBerg; We use OpenStreetMap for mapping on L3MON, IIRC they do not have satellite imagery.
There are 2 solutions for this, firstly you could try and find a tile server that has satellite images and replace the URL in the code, this would render satellite maps instead of flat maps. Or a dual part here maybe we could add a button to view a specific days log in google maps, this should give you more control over what you can do with the data (satellite, etc); though that depends if google allows custom URL building with many coordinate points! 

I'll look into adding a tooltip when you hover over a point on the map at a minimum that will display the coordinates of the hovered point 👍 

@yatharthmaheshwari  - We use GPS Fine Location for GPS logging (it's in the name haha!) - An interesting idea comes to mind, however, When GPS is NOT avaliable we fall back to GEOIP location 🤔 

Thanks, both, I'll close this request now and add a to implement flag, please feel free to add any additional comments 👌
