### ISSUE TITLE
No devices showing up.

### ISSUE THREAD

**Issue by yatharthmaheshwari** [D3VL/L3MON#83]
the apk is installed in phone and all the permissions are given,
but no devices are being shown,

i tried it on multiple phones. but not even one came up.

> i use a virtual machine which has a different ip than my main machine, which might be the problem

if anyone can provide some information of what is going on here and things which might be causing it , i will be very grateful.

**Comment by Jack-Rogers** [comment]
> i use a virtual machine which has a different ip than my main machine, which might be the problem

That's most probably it, try using networking with NAT and use the host computers IP address 👍

**Comment by yatharthmaheshwari** [comment]
ok i will look it up and give it a chance,

BTW i have recorded the "replicating 'java not installed issue' " and  the 2-3 hour long and i just need to edit it..

**Comment by yatharthmaheshwari** [comment]
changing the guest's ip address to hosts 

did'nt work out!

![Capturew](https://user-images.githubusercontent.com/42062688/76708220-32a9fb00-671b-11ea-8b07-ae51bacab6ee.PNG)

**Comment by yatharthmaheshwari** [comment]
i re-installed the apk but that too did not helped.

what do you guy's think do i have to re-make the apk wth the new i cause here i just logined against the ip address

**Comment by Jack-Rogers** [comment]
yes, rebuild the app with the new IP

**Comment by yatharthmaheshwari** [comment]
update: now my vm is using my host ip and i built the app with it and installed it on a samsung device
 but no device's are being shown.....any other ideas why it is happening??

**Comment by Jack-Rogers** [comment]
hmm, this is an odd issue! 
Is there a firewall possibly installed that could be blocking port 22222?

**Comment by yatharthmaheshwari** [comment]
i just sent you some screencast with email replicating the error "yatharthmaheshwari2004@gmail.com"

**Comment by 00itsm00** [comment]
**Hello There,**
I would like to share my exprience but firstly i would like to THANK dev team who made the effort to spare their precious time to actually making this project possible.

**Now Dear All,**

I would like to tell you that i have successfully launched L3MON on 4 servers and they are working perfectly fine without any issues.


![ph](https://user-images.githubusercontent.com/26104191/76891860-1e910580-68a3-11ea-9ccd-1fac77840583.JPG)
.
Few things i would like to share here which needs to be fixed / updated:

1. In devices there's no button to remove / block any device.
2. No update button in clipboard & notification.
![clipb](https://user-images.githubusercontent.com/26104191/76892057-7d567f00-68a3-11ea-891a-d1a43e02167f.JPG)

3. Please update selection / select all check boxes in each side menu so that we ll be able to select desired or all the things to download.

Hope these will be fixed in next update.

Cheers!!.

**Comment by 00itsm00** [comment]
**Hello There,**

I would like to share my exprience but firstly i would like to THANK dev team who made the effort to spare their precious time to actually making this project possible.

**Now Dear All,**

I tried and launched L3MON on 4 of servers and almost 8 to 10 times & they worked perfectly fine without any issues.
![ph](https://user-images.githubusercontent.com/26104191/76891860-1e910580-68a3-11ea-9ccd-1fac77840583.JPG)
.
Few things i would like to share here which needs to be fixed / updated:

1. In devices there's no button to remove / block any device.

2. No update button in clipboard & notification.
![1](https://user-images.githubusercontent.com/26104191/76893040-1d60d800-68a5-11ea-84f0-9b5114e737bc.jpg)

3. Please update selection / select all check boxes in each side menu so that we ll be able to select desired or all the things to download.

Hope these will be fixed in next update.

Cheers!!.

**Comment by 00itsm00** [comment]
**Hello There,**
I would like to share my exprience but firstly i would like to THANK dev team who made the effort to spare their precious time to actually making this project possible.

**Now Dear All,**

I tried and launched L3MON on 4 of servers and almost 8 to 10 times & they worked perfectly fine without any issues.
![ph](https://user-images.githubusercontent.com/26104191/76891860-1e910580-68a3-11ea-9ccd-1fac77840583.JPG)
.
Few things i would like to share here which needs to be fixed / updated:

1. In devices there's no button to remove / block any device.

2. No update button in clipboard & notification.
![1](https://user-images.githubusercontent.com/26104191/76893040-1d60d800-68a5-11ea-84f0-9b5114e737bc.jpg)

3. Please update selection / select all check boxes in each side menu so that we ll be able to select desired or all the things to download.

Hope these will be fixed in next update.

Cheers!!.

> i just sent you some screencast with email replicating the error "[yatharthmaheshwari2004@gmail.com](mailto:yatharthmaheshwari2004@gmail.com)"

**Comment by Jack-Rogers** [comment]
Hey @00itsm00,
Thanks so much for this feedback, could you, however, please create a new issue with this info though, we can address it directly then
Thanks!

**Comment by Jack-Rogers** [comment]
@yatharthmaheshwari I'll have a look through this when I get some time, thank you for taking the time to document the issues for me!

**Comment by 00itsm00** [comment]
> @yatharthmaheshwari I'll have a look through this when I get some time, thank you for taking the time to document the issues for me!

Well i am a new member here and don't know how to open a new issue. Still let me check i ll do it again no problem. Moreover, if you need access to any of my server for testing purposes you are more than welcome.

**Comment by Jack-Rogers** [comment]
@00itsm00 No problems, click [here](https://github.com/D3VL/L3MON/issues/new?assignees=&labels=Feature+Request&template=feature_request.md&title=) or find the green "new issue" button at the top right of this page 👍

**Comment by yatharthmaheshwari** [comment]
@Jack-Rogers I had great time with You and You Really Gave Your Best But after a month of trying i think it is just that my computer is broken or not compitable

**Comment by rnemani96** [comment]
@Jack-Rogers I have no idea how this happened but a few hours back I didn't get java not installed error but started receiving one now and unable to access the file through the browser using NAT as a network for VM oracle java 8. By some means could install L3mon.apk (generated a few hours back) as well as build.s.apk(freshly generated) but in neither cases, I was able to view devices. 
![l3mon change behavior](https://user-images.githubusercontent.com/26691959/77466591-7fcf5080-6e30-11ea-8db9-21d896935cc5.PNG)
![network settings](https://user-images.githubusercontent.com/26691959/77466638-8e1d6c80-6e30-11ea-8790-0f9586161db0.PNG)
![portforwarding](https://user-images.githubusercontent.com/26691959/77466722-ab523b00-6e30-11ea-96eb-c53d7bc930a3.PNG)

**Comment by vaibhav344** [comment]
Same issue is with me I'm not able to see devices made new app changed pc still it doesn't show Can anyone help?
